# trigger:
# - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Visual Studio Enterprise(3bfdcefd-da26-461b-87f7-2cc26378e8be)
  resourceGroup: devops-terraform-rg
  storageAccount: terraforstatefile
  container: terraformstate
  tfstateFile: terraformazdevops.tfstate
  anyTfChanges: false


